# Generated by Django 4.2.7 on 2023-11-23 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krishi', '0008_remove_plantresult_message_plantresult_life_cycle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantresult',
            name='cause',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='plantresult',
            name='name2',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='plantresult',
            name='name',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
